// Copyright (c) 2026 The hislip developers. All rights reserved.
// Project site: https://github.com/gotmc/hislip
// Use of this source code is governed by a MIT-style license that
// can be found in the LICENSE.txt file for the project.

// Package vectors loads the HiSLIP conformance vectors.
//
// The vectors are held as data files rather than as Go literals so that the
// same corpus can drive a firmware test harness or an implementation in another
// language. The files are the authority; this package only parses them.
//
// The vectors are written out by hand from IVI-6.1, never generated by the code
// under test, so that a coding error in the codec cannot be masked by the same
// error in the expectation.
package vectors

import (
	"bufio"
	"bytes"
	"embed"
	"encoding/hex"
	"fmt"
	"strconv"
	"strings"
)

//go:embed headers.txt invalid.txt
var files embed.FS

// emptyMarker stands for a zero-length byte string, which cannot be written as
// an empty field in a whitespace-separated format.
const emptyMarker = "-"

// Header is a valid header vector: the wire bytes and the fields they must
// decode to.
type Header struct {
	Name      string
	Wire      []byte
	Type      uint8
	Control   uint8
	Parameter uint32
	Length    uint64
}

// Rejection reasons used by the malformed vectors.
const (
	// ReasonPrologue means the two-byte "HS" signature is absent.
	ReasonPrologue = "prologue"

	// ReasonShort means fewer than 16 bytes were supplied.
	ReasonShort = "short"
)

// Invalid is a malformed header vector and the reason a decoder must reject it.
type Invalid struct {
	Name   string
	Wire   []byte
	Reason string
}

// Headers returns the valid header vectors from headers.txt.
func Headers() ([]Header, error) {
	records, err := parse("headers.txt", 6)
	if err != nil {
		return nil, err
	}
	out := make([]Header, 0, len(records))
	for _, r := range records {
		wire, err := decodeWire(r.fields[1])
		if err != nil {
			return nil, fmt.Errorf("headers.txt:%d: %w", r.line, err)
		}
		typ, err := parseUint(r.fields[2], 8)
		if err != nil {
			return nil, fmt.Errorf("headers.txt:%d: type: %w", r.line, err)
		}
		control, err := parseUint(r.fields[3], 8)
		if err != nil {
			return nil, fmt.Errorf("headers.txt:%d: control: %w", r.line, err)
		}
		parameter, err := parseUint(r.fields[4], 32)
		if err != nil {
			return nil, fmt.Errorf("headers.txt:%d: parameter: %w", r.line, err)
		}
		length, err := parseUint(r.fields[5], 64)
		if err != nil {
			return nil, fmt.Errorf("headers.txt:%d: length: %w", r.line, err)
		}
		out = append(out, Header{
			Name:      r.fields[0],
			Wire:      wire,
			Type:      uint8(typ),
			Control:   uint8(control),
			Parameter: uint32(parameter),
			Length:    length,
		})
	}
	return out, nil
}

// Invalids returns the malformed header vectors from invalid.txt.
func Invalids() ([]Invalid, error) {
	records, err := parse("invalid.txt", 3)
	if err != nil {
		return nil, err
	}
	out := make([]Invalid, 0, len(records))
	for _, r := range records {
		wire, err := decodeWire(r.fields[1])
		if err != nil {
			return nil, fmt.Errorf("invalid.txt:%d: %w", r.line, err)
		}
		reason := r.fields[2]
		switch reason {
		case ReasonPrologue, ReasonShort:
		default:
			return nil, fmt.Errorf("invalid.txt:%d: unknown reason %q", r.line, reason)
		}
		out = append(out, Invalid{Name: r.fields[0], Wire: wire, Reason: reason})
	}
	return out, nil
}

// record is one parsed line.
type record struct {
	line   int
	fields []string
}

// parse reads a vector file, discarding comments and blank lines, and requires
// every record to have exactly want fields.
func parse(name string, want int) ([]record, error) {
	data, err := files.ReadFile(name)
	if err != nil {
		return nil, err
	}
	var out []record
	scanner := bufio.NewScanner(bytes.NewReader(data))
	for line := 1; scanner.Scan(); line++ {
		text := scanner.Text()
		if i := strings.IndexByte(text, '#'); i >= 0 {
			text = text[:i]
		}
		fields := strings.Fields(text)
		if len(fields) == 0 {
			continue
		}
		if len(fields) != want {
			return nil, fmt.Errorf(
				"%s:%d: got %d fields, want %d: %q",
				name, line, len(fields), want, text,
			)
		}
		out = append(out, record{line: line, fields: fields})
	}
	if err := scanner.Err(); err != nil {
		return nil, err
	}
	if len(out) == 0 {
		return nil, fmt.Errorf("%s: no vectors found", name)
	}
	return out, nil
}

// decodeWire converts a hex field to bytes, treating emptyMarker as empty.
func decodeWire(field string) ([]byte, error) {
	if field == emptyMarker {
		return nil, nil
	}
	b, err := hex.DecodeString(field)
	if err != nil {
		return nil, fmt.Errorf("bad hex %q: %w", field, err)
	}
	return b, nil
}

// parseUint accepts decimal or 0x-prefixed hex.
func parseUint(field string, bits int) (uint64, error) {
	return strconv.ParseUint(field, 0, bits)
}
