// Copyright (c) 2026 The hislip developers. All rights reserved.
// Project site: https://github.com/gotmc/hislip
// Use of this source code is governed by a MIT-style license that
// can be found in the LICENSE.txt file for the project.

package protocol

import (
	"bytes"
	"errors"
	"io"
	"testing"
)

// goldenHeaders are byte-exact vectors. They are written out by hand from
// IVI-6.1 rather than generated by this package, so that a coding error in the
// codec cannot be masked by the same error in the expectation.
var goldenHeaders = []struct {
	name   string
	wire   []byte
	header Header
}{
	{
		// Initialize, client version 1.0, vendor ID "GT", sub-address
		// "hislip0" of seven bytes.
		name: "Initialize",
		wire: []byte{
			'H', 'S', // prologue
			0x00,                   // type 0, Initialize
			0x00,                   // control code
			0x01, 0x00, 0x47, 0x54, // version 1.0, vendor "GT"
			0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x07, // length 7
		},
		header: Header{
			Type:      Initialize,
			Control:   0,
			Parameter: 0x01004754,
			Length:    7,
		},
	},
	{
		// InitializeResponse, negotiated version 1.0, session ID 0x1234,
		// control code 0 meaning the server prefers Synchronized Mode.
		name: "InitializeResponse",
		wire: []byte{
			'H', 'S',
			0x01,
			0x00,
			0x01, 0x00, 0x12, 0x34,
			0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
		},
		header: Header{
			Type:      InitializeResponse,
			Control:   0,
			Parameter: 0x01001234,
			Length:    0,
		},
	},
	{
		// DataEnd carrying the initial MessageID, RMT-delivered set, four
		// payload bytes.
		name: "DataEnd",
		wire: []byte{
			'H', 'S',
			0x07,
			0x01,
			0xff, 0xff, 0xff, 0x00,
			0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x04,
		},
		header: Header{
			Type:      DataEnd,
			Control:   ControlRMTDelivered,
			Parameter: uint32(InitialMessageID),
			Length:    4,
		},
	},
	{
		// AsyncStatusResponse, status byte 0x50, no payload.
		name: "AsyncStatusResponse",
		wire: []byte{
			'H', 'S',
			0x16,
			0x50,
			0x00, 0x00, 0x00, 0x00,
			0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
		},
		header: Header{
			Type:      AsyncStatusResponse,
			Control:   0x50,
			Parameter: 0,
			Length:    0,
		},
	},
	{
		// A maximal payload length, to confirm the 64-bit field is decoded
		// whole and is not truncated or sign-extended.
		name: "MaxLength",
		wire: []byte{
			'H', 'S',
			0x06,
			0x00,
			0x00, 0x00, 0x00, 0x00,
			0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff,
		},
		header: Header{
			Type:      Data,
			Control:   0,
			Parameter: 0,
			Length:    0xffffffffffffffff,
		},
	},
}

func TestGoldenHeadersDecode(t *testing.T) {
	for _, tc := range goldenHeaders {
		t.Run(tc.name, func(t *testing.T) {
			if len(tc.wire) != HeaderSize {
				t.Fatalf("vector is %d bytes, want %d", len(tc.wire), HeaderSize)
			}
			got, err := DecodeHeader(tc.wire)
			if err != nil {
				t.Fatalf("DecodeHeader() error = %v", err)
			}
			if got != tc.header {
				t.Errorf("DecodeHeader() = %+v, want %+v", got, tc.header)
			}
		})
	}
}

func TestGoldenHeadersEncode(t *testing.T) {
	for _, tc := range goldenHeaders {
		t.Run(tc.name, func(t *testing.T) {
			var buf [HeaderSize]byte
			if err := tc.header.Encode(buf[:]); err != nil {
				t.Fatalf("Encode() error = %v", err)
			}
			if !bytes.Equal(buf[:], tc.wire) {
				t.Errorf("Encode() = % x, want % x", buf[:], tc.wire)
			}
		})
	}
}

func TestHeaderRoundTrip(t *testing.T) {
	for _, tc := range goldenHeaders {
		t.Run(tc.name, func(t *testing.T) {
			var buf [HeaderSize]byte
			var w bytes.Buffer
			if err := WriteHeader(&w, tc.header, &buf); err != nil {
				t.Fatalf("WriteHeader() error = %v", err)
			}
			got, err := ReadHeader(&w, &buf)
			if err != nil {
				t.Fatalf("ReadHeader() error = %v", err)
			}
			if got != tc.header {
				t.Errorf("round trip = %+v, want %+v", got, tc.header)
			}
		})
	}
}

func TestDecodeHeaderRejectsBadPrologue(t *testing.T) {
	tests := []struct {
		name string
		wire []byte
	}{
		{"zero", make([]byte, HeaderSize)},
		{"lowercase", []byte("hs\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00")},
		{"swapped", []byte("SH\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00")},
		{"firstOnly", []byte("HX\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00")},
	}
	for _, tc := range tests {
		t.Run(tc.name, func(t *testing.T) {
			if _, err := DecodeHeader(tc.wire); !errors.Is(err, ErrInvalidPrologue) {
				t.Errorf("DecodeHeader() error = %v, want ErrInvalidPrologue", err)
			}
		})
	}
}

func TestDecodeHeaderRejectsShortBuffer(t *testing.T) {
	full := goldenHeaders[0].wire
	for n := 0; n < HeaderSize; n++ {
		if _, err := DecodeHeader(full[:n]); !errors.Is(err, ErrShortBuffer) {
			t.Errorf("DecodeHeader(%d bytes) error = %v, want ErrShortBuffer", n, err)
		}
	}
}

func TestEncodeRejectsShortBuffer(t *testing.T) {
	h := goldenHeaders[0].header
	for n := 0; n < HeaderSize; n++ {
		b := make([]byte, n)
		if err := h.Encode(b); !errors.Is(err, ErrShortBuffer) {
			t.Errorf("Encode(%d bytes) error = %v, want ErrShortBuffer", n, err)
		}
	}
}

func TestReadHeaderTruncatedStream(t *testing.T) {
	full := goldenHeaders[0].wire
	for n := 1; n < HeaderSize; n++ {
		var buf [HeaderSize]byte
		_, err := ReadHeader(bytes.NewReader(full[:n]), &buf)
		if !errors.Is(err, io.ErrUnexpectedEOF) {
			t.Errorf("ReadHeader(%d bytes) error = %v, want io.ErrUnexpectedEOF", n, err)
		}
	}
	var buf [HeaderSize]byte
	if _, err := ReadHeader(bytes.NewReader(nil), &buf); !errors.Is(err, io.EOF) {
		t.Errorf("ReadHeader(empty) error = %v, want io.EOF", err)
	}
}

func TestHeaderAccessors(t *testing.T) {
	h := Header{Parameter: uint32(InitialMessageID), Control: ControlRMTDelivered}
	if got := h.MessageID(); got != InitialMessageID {
		t.Errorf("MessageID() = %#x, want %#x", got, InitialMessageID)
	}
	if !h.RMTDelivered() {
		t.Error("RMTDelivered() = false, want true")
	}
	h.Control = 0
	if h.RMTDelivered() {
		t.Error("RMTDelivered() = true, want false")
	}
}

// TestDecodeHeaderAcceptsRejectableMessages records the deliberate decision
// that decoding does not validate the message type or the length. A receiver
// must decode a header it intends to reject so that it can consume the payload
// and stay synchronised with the peer.
func TestDecodeHeaderAcceptsRejectableMessages(t *testing.T) {
	for _, typ := range []MessageType{40, 127, 128, 255} {
		wire := make([]byte, HeaderSize)
		wire[0], wire[1] = 'H', 'S'
		wire[2] = byte(typ)
		h, err := DecodeHeader(wire)
		if err != nil {
			t.Fatalf("DecodeHeader(type %d) error = %v, want nil", typ, err)
		}
		if h.Type != typ {
			t.Errorf("Type = %d, want %d", h.Type, typ)
		}
	}
}
